import babelParser from '@babel/eslint-parser';
import litPlugin from 'eslint-plugin-lit';
import jsdocPlugin from 'eslint-plugin-jsdoc';

export default [
  {
    ignores: ['test/*.js', '.eslintrc.js', 'coverage/**', 'dist/**', 'build/**', 'node_modules/**']
  },
  {
    files: ['src/**/*.js'],
    languageOptions: {
      parser: babelParser,
      parserOptions: {
        ecmaVersion: 2018,
        sourceType: 'module',
        requireConfigFile: false,
        babelOptions: {
          babelrc: false,
          configFile: false
        }
      },
      globals: {
        Atomics: 'readonly',
        SharedArrayBuffer: 'readonly'
      }
    },
    plugins: {
      lit: litPlugin,
      jsdoc: jsdocPlugin
    },
    rules: {
      // ESLint recommended rules
      'accessor-pairs': 'error',
      'array-bracket-newline': 'error',
      'array-bracket-spacing': 'error',
      'array-callback-return': 'error',
      'array-element-newline': 'error',
      'arrow-body-style': 'error',
      'arrow-parens': 'error',
      'arrow-spacing': ['error', { before: true, after: true }],
      'block-scoped-var': 'error',
      'block-spacing': 'error',
      'brace-style': 'error',
      'camelcase': 'error',
      'comma-spacing': ['error', { before: false, after: true }],
      'comma-style': ['error', 'last'],
      'complexity': 'error',
      'computed-property-spacing': 'error',
      'consistent-return': 'error',
      'consistent-this': 'error',
      'curly': 'error',
      'default-case': 'error',
      'default-param-last': 'error',
      'dot-location': 'error',
      'dot-notation': 'error',
      'eol-last': ['error', 'always'],
      'eqeqeq': 'error',
      'func-call-spacing': 'error',
      'func-name-matching': 'error',
      'function-paren-newline': 'error',
      'generator-star-spacing': 'error',
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'id-length': 'error',
      'id-match': 'error',
      'implicit-arrow-linebreak': 'error',
      'indent': ['error', 2, { SwitchCase: 1 }],
      'init-declarations': 'error',
      'keyword-spacing': ['error', { before: true, after: true }],
      'line-comment-position': 'error',
      'linebreak-style': ['error', 'unix'],
      'lines-around-comment': 'error',
      'lines-between-class-members': ['error', 'always'],
      'max-classes-per-file': 'error',
      'max-depth': 'error',
      'max-lines': 'error',
      'max-nested-callbacks': 'error',
      'max-params': 'error',
      'max-statements-per-line': 'error',
      'new-cap': 'error',
      'new-parens': 'error',
      'newline-per-chained-call': 'error',
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-await-in-loop': 'error',
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-confusing-arrow': 'error',
      'no-console': 'error',
      'no-constructor-return': 'error',
      'no-continue': 'error',
      'no-div-regex': 'error',
      'no-duplicate-imports': 'error',
      'no-else-return': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-extra-parens': 'error',
      'no-floating-decimal': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-inline-comments': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-magic-numbers': ['error', { ignore: [-1, 0, 1, 2] }],
      'no-mixed-operators': 'error',
      'no-multi-assign': 'error',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-multiple-empty-lines': 'error',
      'no-nested-ternary': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-object': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'error',
      'no-plusplus': 'error',
      'no-proto': 'error',
      'no-restricted-globals': 'error',
      'no-restricted-imports': 'error',
      'no-restricted-properties': 'error',
      'no-restricted-syntax': 'error',
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': 'error',
      'no-tabs': 'error',
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-trailing-spaces': 'error',
      'no-undef-init': 'error',
      'no-underscore-dangle': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': 'error',
      'no-unused-expressions': 'error',
      'no-use-before-define': 'error',
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'no-warning-comments': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': 'error',
      'object-curly-newline': 'error',
      'object-property-newline': 'error',
      'object-shorthand': 'error',
      'operator-assignment': 'error',
      'operator-linebreak': 'error',
      'padding-line-between-statements': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-destructuring': 'error',
      'prefer-exponentiation-operator': 'error',
      'prefer-named-capture-group': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'radix': 'error',
      'require-await': 'error',
      'require-unicode-regexp': 'error',
      'rest-spread-spacing': ['error', 'never'],
      'semi': ['error', 'always'],
      'semi-spacing': 'error',
      'semi-style': ['error', 'last'],
      'sort-vars': 'error',
      'space-before-blocks': 'error',
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'spaced-comment': ['error', 'always'],
      'strict': 'error',
      'switch-colon-spacing': 'error',
      'symbol-description': 'error',
      'template-curly-spacing': ['error', 'never'],
      'template-tag-spacing': ['error', 'never'],
      'unicode-bom': ['error', 'never'],
      'vars-on-top': 'error',
      'wrap-iife': 'error',
      'wrap-regex': 'error',
      'yield-star-spacing': 'error',
      'yoda': ['error', 'never'],
      
      // JSDoc rules
      'jsdoc/check-access': 'warn',
      'jsdoc/check-alignment': 'warn',
      'jsdoc/check-param-names': 'warn',
      'jsdoc/check-property-names': 'warn',
      'jsdoc/empty-tags': 'warn',
      'jsdoc/implements-on-classes': 'warn',
      'jsdoc/no-multi-asterisks': 'warn',
      'jsdoc/no-undefined-types': ['warn', { definedTypes: ['CustomEvent', 'HTMLElement', 'Element'] }],
      'jsdoc/require-asterisk-prefix': 'warn',
      'jsdoc/require-description-complete-sentence': 'warn',
      'jsdoc/require-jsdoc': 'warn',
      'jsdoc/require-param': ['error', { checkRestProperty: true }],
      'jsdoc/require-param-description': 'warn',
      'jsdoc/require-param-name': 'warn',
      'jsdoc/require-param-type': 'warn',
      'jsdoc/require-property': 'warn',
      'jsdoc/require-property-description': 'warn',
      'jsdoc/require-property-type': 'warn',
      'jsdoc/require-returns': 'warn',
      'jsdoc/require-returns-check': 'warn'
    }
  }
];
